- name: Install Syncthing with addons
  tags: syncthing
  become: true
  block:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install Semaphore package from the internet
      ansible.builtin.apt:
        deb: https://github.com/semaphoreui/semaphore/releases/download/v2.10.35/semaphore_2.10.35_linux_amd64.deb

    - name: Create Unit file from template
      check_mode: false
      ansible.builtin.template:
        src: '{{ role_path }}/templates/unit.j2'
        dest: '/etc/systemd/system/semaphore.service'
        mode: '0664'

    - name: Start Semaphore service
      ansible.builtin.systemd_service:
        state: started
        enabled: true
        daemon_reload: true
        name: semaphore
