- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true
  run_once: true
  #ignore_errors: true

- name: Install required system packages
  apt:
    pkg:
      - git
      - gh
      - jq
      - tldr
      - sudo
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - virtualenv
      - python3-pip
      - python3-setuptools
      - python3-apt
      - neofetch
    state: latest
    update_cache: true
  #run_once: true
  #ignore_errors: true
# TODO:
# - set of common packages for all hosts
# - possibility for adding own package names from site
