- name: Install standard packages
  ansible.builtin.package:
    name: "{{ standard_packages }}"
    state: present
  become: true

- name: Install additional packages (if provided)
  ansible.builtin.package:
    name: "{{ extra_packages }}"
    state: present
  when: extra_packages | length > 0
  become: true