- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - git
      - jq
      - sudo
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - virtualenv
      - python3-pip
      - python3-setuptools
      - python3-apt
      - neofetch
    state: present
    update_cache: true
# TODO:
# - set of common packages for all hosts
# - possibility for adding own package names from site
