- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true
  run_once: true
  #ignore_errors: true

- name: Install required system packages
  apt:
    pkg:
      - git
      - gh
      - jq
      - tldr
      - sudo
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - neofetch
    state: latest
    update_cache: true
  run_once: true
  #ignore_errors: true
