---
- hosts: localhost
  gather_facts: no

  tasks:
    - name: Get site path
      shell: pwd
      register: site_directory

- import_playbook: ../../main.yml
  vars:
    site_dir: "{{ hostvars['localhost']['site_directory'].stdout }}"