- name: Start compose
  community.docker.docker_compose:
    project_name: tubearchivist
    state: present
    definition:
      services:
        tubearchivist:
          container_name: tubearchivist
          restart: unless-stopped
          image: bbilly1/tubearchivist:v0.4.11
          ports:
            - 8000:8000
          volumes:
            - nfs-tubearchivist-media:/youtube
            - nfs-tubearchivist-cache:/cache
          environment:
            - ES_URL=http://archivist-es:9200
            - REDIS_HOST=archivist-redis
            - HOST_UID=1000
            - HOST_GID=1000
            - 'TA_HOST={{ ta_origins }}'
            - 'TA_USERNAME={{ ta_username }}'
            - 'TA_PASSWORD={{ ta_password }}'
            - 'ELASTIC_PASSWORD={{ es_password }}'
            - TZ=Europe/Warsaw
          healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
            interval: 2m
            timeout: 10s
            retries: 3
            start_period: 30s
          depends_on:
            - archivist-es
            - archivist-redis
        archivist-redis:
          image: redis/redis-stack-server
          container_name: archivist-redis
          restart: unless-stopped
          expose:
            - '6379'
          volumes:
            - nfs-tubearchivist-redis:/data
          depends_on:
            - archivist-es
        archivist-es:
          image: bbilly1/tubearchivist-es
          container_name: archivist-es
          restart: unless-stopped
          environment:
            - 'ELASTIC_PASSWORD={{ es_password }}'
            - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
            - 'xpack.security.enabled=true'
            - 'discovery.type=single-node'
            - 'path.repo=/usr/share/elasticsearch/data/snapshot'
          ulimits:
            memlock:
              soft: -1
              hard: -1
          volumes:
            - nfs-tubearchivist-es:/usr/share/elasticsearch/data
          expose:
            - '9200'
      volumes:
        nfs-tubearchivist-es:
          driver: 'local'
          driver_opts:
            type: nfs
            o: 'addr={{ nas_ip }},rw,nfsvers=4,no_all_squash'
            device: ':/mnt/docker-volumes/tubearchivist/es'
        nfs-tubearchivist-redis:
          driver: 'local'
          driver_opts:
            type: nfs
            o: 'addr={{ nas_ip }},rw,nfsvers=4,no_all_squash'
            device: ':/mnt/docker-volumes/tubearchivist/redis'
        nfs-tubearchivist-cache:
          driver: 'local'
          driver_opts:
            type: nfs
            o: 'addr={{ nas_ip }},rw,nfsvers=4,no_all_squash'
            device: ':/mnt/docker-volumes/tubearchivist/cache'
        nfs-tubearchivist-media:
          driver: 'local'
          driver_opts:
            type: nfs
            o: 'addr={{ nas_ip }},rw,nfsvers=4,no_all_squash'
            device: ':/mnt/docker-volumes/tubearchivist/media'
  register: output
  become: true
