- name: Update
  become: true
  hosts: all
  tasks:
    - name: Update system packages
      ansible.builtin.yum:
        name: '*'
        state: latest
      when: ansible_os_family == 'RedHat'

    - name: Update system packages
      ansible.builtin.apt:
        upgrade: dist
      when: ansible_os_family == 'Debian'

    - name: Clean up unused packages
      ansible.builtin.package:
        name: '*'
        state: absent
      when: ansible_os_family in ['RedHat', 'Debian']