- name: Set variables
  hosts: localhost
  tasks:
    - name: Include vars
      ansible.builtin.include_vars: '{{ site_dir }}/vars.yml'
- name: Play for virtual machines
  hosts: vm_root
  become: true
  gather_facts: true
  roles:
    - role: network
    - role: packages
    - role: users
    - role: shell
    # - role: common/proxmox-agent
- name: Play for lxc_
  hosts: lxc_root
  become: true
  gather_facts: true
  roles:
    - network
    - packages
    - users
    - shell
