- name: Set variables
  hosts: localhost
  tasks:
    - include_vars: "{{ site_dir }}/vars.yml"

- hosts: vm_root
  become: true
  gather_facts: yes
  roles:
    - role: common/packages
    - role: common/users
    - role: common/networking
    - role: common/proxmox-agent

- hosts: lxc_root
  become: true
  gather_facts: yes
  roles:
    - role: common/packages
    - role: common/users
    - role: common/networking
