---
apiVersion: v1
kind: Namespace
metadata:
  name: tube-archivist
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tubearchivist-config
  namespace: tube-archivist
data:
  TA_HOST: "k3s-master.lukcic.net https://ta.lukcic.pl"
  ES_URL: "http://tubearchivist-es:9200"
  REDIS_CON: "redis://tubearchivist-redis:6379"
  HOST_UID: "568"
  HOST_GID: "568"
  TZ: "Europe/Warsaw"
  ES_SNAPSHOT_DIR: "/usr/share/elasticsearch/data/snapshot"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tube-archivist
  namespace: tube-archivist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tube-archivist
  template:
    metadata:
      labels:
        app: tube-archivist
    spec:
      containers:
        - name: tube-archivist
          image: bbilly1/tubearchivist
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: tubearchivist-config
            - secretRef:
                name: tubearchivist-secrets
          volumeMounts:
            - name: media
              mountPath: /youtube
          resources:
            limits:
              cpu: "2"
              memory: "2G"
            requests:
              cpu: "1"
              memory: "1G"
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: tubearchivist-media
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tubearchivist-media
  labels:
    type: local
spec:
  storageClassName: "manual"
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/tube-archivist/media"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tubearchivist-media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: tubearchivist-secrets
  namespace: tube-archivist
type: Opaque
data:
  TA_USERNAME: "bHVrY2lj"
  TA_PASSWORD: "VmVyeXNlY3JldDEh"
  ELASTIC_PASSWORD: "VmVyeXNlY3JldDE="
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: tubearchivist-redis
# spec:
#   storageClassName: "manual"
#   capacity:
#     storage: 100Gi
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: "/mnt/tube-archivist/redis"
#     type: DirectoryOrCreate
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: tubearchivist-redis
#   namespace: tube-archivist
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: "manual"
#   resources:
#     requests:
#       storage: 100Gi

---
apiVersion: v1
kind: Service
metadata:
  name: tube-archivist
  namespace: tube-archivist
spec:
  selector:
    app: tube-archivist
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tubearchivist-ingress
  namespace: tube-archivist
  annotations:
    kubernetes.io/ingress.className: "traefik"
spec:
  rules:
    - host: "ta.lukcic.pl"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: tube-archivist
                port:
                  number: 8000
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tube-archivist
  namespace: default
spec:
  secretName: tube-archivist-lukcic-pl-ssl-cert
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - ta.lukcic.pl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tubearchivist-redis
  namespace: tube-archivist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tubearchivist-redis
  template:
    metadata:
      labels:
        app: tubearchivist-redis
    spec:
      containers:
        - name: redis
          image: redis/redis-stack-server
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
      # volumes:
      #   - name: redis-data
      #     persistentVolumeClaim:
      #       claimName: tubearchivist-redis
---
apiVersion: v1
kind: Service
metadata:
  name: tubearchivist-redis
  namespace: tube-archivist
spec:
  selector:
    app: "tubearchivist-redis"
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tubearchivist-es
  namespace: tube-archivist
spec:
  serviceName: tubearchivist-es
  replicas: 1
  selector:
    matchLabels:
      app: "tubearchivist-es"
  template:
    metadata:
      labels:
        app: "tubearchivist-es"
    spec:
      initContainers:
        - name: init-tubearchivist-es
          image: busybox
          command:
            [
              "/bin/sh",
              "-c",
              "chown -R 1000:1000 /usr/share/elasticsearch/data && chmod -R 755 /usr/share/elasticsearch/data",
            ]
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
          securityContext:
            runAsUser: 0
      containers:
        - name: elasticsearch
          image: bbilly1/tubearchivist-es
          ports:
            - containerPort: 9200
          env:
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tubearchivist-secrets
                  key: ELASTIC_PASSWORD
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: xpack.security.enabled
              value: "true"
            - name: discovery.type
              value: "single-node"
            - name: path.repo
              value: "/usr/share/elasticsearch/data/snapshot"
            # - name: HOST_UID
            #   value: "568"
            # - name: HOST_GID
            #   value: "568"
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
          resources:
            limits:
              cpu: "1000m"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: tubearchivist-es
---
apiVersion: v1
kind: Service
metadata:
  name: tubearchivist-es
  namespace: tube-archivist
spec:
  selector:
    app: "tubearchivist-es"
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tubearchivist-es
spec:
  storageClassName: "manual"
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/tube-archivist/es"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tubearchivist-es
  namespace: tube-archivist
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "manual"
  resources:
    requests:
      storage: 100Gi
