---
apiVersion: v1
kind: Namespace
metadata:
  name: tube-archivist
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tube-archivist-config
  namespace: tube-archivist
data:
  TA_HOST: "k3s-master.lukcic.net k3s-node01.lukcic.net ta.lukcic.pl"
  ES_URL: "http://tube-archivist-elasticsearch:9200"
  REDIS_CON: "redis://tube-archivist-redis:6379"
  HOST_UID: "568"
  HOST_GID: "568"
  TZ: "Europe/Warsaw"
  ES_SNAPSHOT_DIR: "/usr/share/elasticsearch/data/snapshot"
---
apiVersion: v1
kind: Secret
metadata:
  name: tube-archivist-secrets
  namespace: tube-archivist
type: Opaque
data:
  TA_USERNAME: "bHVrY2lj"
  TA_PASSWORD: "VmVyeXNlY3JldDEh"
  ELASTIC_PASSWORD: "VmVyeXNlY3JldDE="
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tube-archivist-ingress
  namespace: tube-archivist
  labels:
    app.kubernetes.io/name: tube-archivist
  # annotations:
  #   kubernetes.io/ingress.className: "traefik"
spec:
  tls:
    - hosts:
        - ta.lukcic.pl
      secretName: tube-archivist-lukcic-pl-ssl-cert
  rules:
    - host: "ta.lukcic.pl"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: tube-archivist
                port:
                  number: 8000
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tube-archivist
  namespace: tube-archivist
spec:
  secretName: tube-archivist-lukcic-pl-ssl-cert
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - ta.lukcic.pl
