apiVersion: v1
kind: PersistentVolume
metadata:
  name: tube-archivist-elasticsearch
  labels:
    type: local
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/tube-archivist/elasticsearch
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tube-archivist-elasticsearch
  namespace: tube-archivist
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: tube-archivist-elasticsearch
  namespace: tube-archivist
spec:
  selector:
    app: tube-archivist-elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tube-archivist-elasticsearch
  namespace: tube-archivist
spec:
  serviceName: tube-archivist-elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: "tube-archivist-elasticsearch"
  template:
    metadata:
      labels:
        app: "tube-archivist-elasticsearch"
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-node1
      initContainers:
        - name: init-tube-archivist-elasticsearch
          image: busybox
          command:
            [
              "/bin/sh",
              "-c",
              "chown -R 1000:1000 /usr/share/elasticsearch/data && chmod -R 755 /usr/share/elasticsearch/data",
            ]
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
          securityContext:
            runAsUser: 0
      containers:
        - name: elasticsearch
          image: bbilly1/tubearchivist-es
          ports:
            - containerPort: 9200
          env:
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tube-archivist-secrets
                  key: ELASTIC_PASSWORD
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: xpack.security.enabled
              value: "true"
            - name: discovery.type
              value: "single-node"
            - name: path.repo
              value: "/usr/share/elasticsearch/data/snapshot"
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
          resources:
            limits:
              cpu: "1000m"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: tube-archivist-elasticsearch
