apiVersion: v1
kind: PersistentVolume
metadata:
  name: tube-archivist-media
  labels:
    type: local
spec:
  storageClassName: "manual"
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/tube-archivist/media"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tube-archivist-media
  namespace: tube-archivist
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tube-archivist-cache
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/tube-archivist/cache
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tube-archivist-cache
  namespace: tube-archivist
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: tube-archivist
  namespace: tube-archivist
  labels:
    app: tube-archivist
spec:
  selector:
    app: tube-archivist
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tube-archivist
  namespace: tube-archivist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tube-archivist
  template:
    metadata:
      labels:
        app: tube-archivist
    spec:
      containers:
        - name: tube-archivist
          image: bbilly1/tubearchivist
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: tube-archivist-config
            - secretRef:
                name: tube-archivist-secrets
          volumeMounts:
            - name: media
              mountPath: /youtube
            - name: cache
              mountPath: /cache
          resources:
            limits:
              cpu: "2000m"
              memory: "2Gi"
            requests:
              cpu: "1000m"
              memory: "1Gi"
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: tube-archivist-media
        - name: cache
          persistentVolumeClaim:
            claimName: tube-archivist-cache
