- name: Configure virtual machines
  ansible.builtin.include_tasks:
    file: setup-debian-vm.yml
  when:
    - ansible_os_family == 'Debian'
    - host_type == 'vm'

- name: Install and configure containerd
  ansible.builtin.include_tasks:
    file: containerd.yml
  when:
    - host_type == 'vm'

- name: Install and hold kube* packages
  ansible.builtin.include_tasks:
    file: kube-packages.yml
  when:
    - host_type == 'vm'

- name: Check if Kubernetes has already been initialized.
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_init

- name: Setup control plane
  ansible.builtin.include_tasks:
    file: k8s-control-plane.yml
  when:
    - host_type == 'vm'
    - not kubernetes_init.stat.exists

- name: Check if tigera-operator namespace exists
  become: true
  become_user: '{{ admin_user }}'
  ansible.builtin.command: kubectl get ns tigera-operator
  register: calico_exists
  ignore_errors: true
  changed_when: >
    calico_exists.rc != 0 and
    'Error from server (NotFound): namespaces "tigera-operator" not found' in calico_exists.stderr
  failed_when: >
    calico_exists.rc != 0 and
    'Error from server (NotFound): namespaces "tigera-operator" not found' not in calico_exists.stderr

- name: Install Calico network plugin
  ansible.builtin.include_tasks:
    file: calico.yml
  when:
    - calico_exists.changed
