- name: Install required packages
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - jq
      - git-lfs
      - make
      - g++
      - libpq-dev
      - ansible
      - git-crypt
    state: latest
    update_cache: true
  run_once: true
  tags: install
