- name: Cleanup all user authorized keys
  become_user: "{{ user.name }}"
  file:
    path: ~{{ user.name }}/.ssh/authorized_keys
    state: absent
  when: users_created is changed

- name: Find all auth keys in the directory for {{ user.name }}
  become: false
  delegate_to: localhost
  find:
    paths: "{{ role_path }}/files/keys/{{ user.name }}/"
    patterns: "*.pub"
    file_type: file
  register: user_keys_paths
  when: users_created is changed

- name: Copy auth keys for {{ user.name }}
  authorized_key:
    user: "{{ user.name }}"
    state: present
    key: "{{ lookup('file', item.path) }}"
  with_items: "{{ user_keys_paths.files }}"
  when: users_created is changed
