- name: Cleanup all user authorized keys
  become: true
  become_user: '{{ user.name }}'
  ansible.builtin.file:
    path: ~{{ user.name }}/.ssh/authorized_keys
    state: absent
  # when: users_created is changed # noqa: no-handler

- name: Find all auth keys in the directory for {{ user.name }}
  become: false
  delegate_to: localhost
  ansible.builtin.find:
    paths: '{{ role_path }}/files/keys/{{ user.name }}/'
    patterns: '*.pub'
    file_type: file
  register: user_keys_paths
  # when: users_created is changed # noqa: no-handler

- name: Copy auth keys for {{ user.name }}
  ansible.posix.authorized_key:
    user: '{{ user.name }}'
    state: present
    key: "{{ lookup('file', item.path) }}"
  with_items: '{{ user_keys_paths.files }}'
  # when: users_created is changed # noqa: no-handler
