- name: Create wheel group
  ansible.builtin.group:
    name: wheel
    state: present

- name: Sudo without password for wheel group
  ansible.builtin.copy:
    content: '%wheel ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: /etc/sudoers.d/wheel-nopasswd
    mode: '0440'

- name: Create user groups
  ansible.builtin.group:
    name: '{{ item.name }}'
    state: present
    gid: '{{ item.uid }}'
  with_items: '{{ all_users }}'

- name: Create basic users accounts
  ansible.builtin.user:
    name: '{{ item.name }}'
    shell: '{{ item.shell }}'
    uid: '{{ item.uid }}'
    group: '{{ item.name }}'
    groups: '{{ item.groups }}'
    append: true
  with_items: '{{ all_users }}'
  register: users_created

- name: Add SSH authorized keys to users
  ansible.builtin.include_tasks: add_ssh_keys.yml
  loop: '{{ all_users }}'
  loop_control:
    loop_var: user
  when: user.shell != "/usr/sbin/nologin"
