- include_vars: "{{ site_dir }}/vars.yml"

- name: Restart host
  ansible.builtin.reboot:
  listen: "Reboot and wait"

- name: Wait for server to restart
  wait_for:
    port: 22
    host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
    delay: 10
  connection: local
  become: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  listen: "Reboot and wait"
