all:
  hosts:
    k8s-controller:
      ansible_host: 192.168.254.170
      ip: 192.168.254.170
      access_ip: 192.168.254.170
      ansible_user: debian
      ansible_private_key_file: ~/.ssh/lukcic_id_ed25519.pem
      ansible_python_interpreter: /usr/bin/python3
    k8s-1:
      ansible_host: 192.168.254.171
      ip: 192.168.254.171
      access_ip: 192.168.254.171
      ansible_user: debian
      ansible_private_key_file: ~/.ssh/lukcic_id_ed25519.pem
      ansible_python_interpreter: /usr/bin/python3
    k8s-2:
      ansible_host: 192.168.254.172
      ip: 192.168.254.172
      access_ip: 192.168.254.172
      ansible_user: debian
      ansible_private_key_file: ~/.ssh/lukcic_id_ed25519.pem
      ansible_python_interpreter: /usr/bin/python3
    k8s-3:
      ansible_host: 192.168.254.173
      ip: 192.168.254.173
      access_ip: 192.168.254.173
      ansible_user: debian
      ansible_private_key_file: ~/.ssh/lukcic_id_ed25519.pem
      ansible_python_interpreter: /usr/bin/python3
  children:
    kube_control_plane:
      hosts:
        k8s-controller:
        k8s-1:
    kube_node:
      hosts:
        k8s-controller:
        k8s-1:
        k8s-2:
        k8s-3:
    etcd:
      hosts:
        k8s-controller:
        k8s-1:
        k8s-2:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
