- name: Configure hosts
  become: true
  hosts: vm_root
  vars_files: secrets.yml
  roles:
    - common/packages # noqa: syntax-check[specific]
    - common/users
    - common/shell

- name: Initialize PVE cluster
  become: true
  become_user: root
  hosts: vm_ansible
  vars_files: secrets.yml
  roles:
    - tube-archivist # noqa: syntax-check[specific]
