- name: Create aliases for root
  ansible.builtin.lineinfile:
    path: /root/.bashrc
    line: "alias {{ item.key }}=\u0027{{ item.value }}\u0027"
    owner: root
    state: present
    insertafter: EOF
    create: true
    mode: '0600'
  with_dict: '{{ aliases }}'

- name: Create aliases for zsh_user
  ansible.builtin.lineinfile:
    path: "/home/{{ zsh_user }}/.bashrc"
    line: "alias {{ item.key }}=\u0027{{ item.value }}\u0027"
    owner: "{{ zsh_user }}"
    state: present
    insertafter: EOF
    create: true
    mode: '0600'
  with_dict: '{{ aliases }}'
