- name: Install required system packages
  apt:
    pkg:
      - zsh
      - vim
      - tmux
      - bat
    state: latest
    update_cache: true
  run_once: true
  ignore_errors: true

- name: Create autoinstall directory
  become_user: lukcic
  file:
    path: /home/lukcic/autoinstall
    state: directory
    mode: "0700"

- name: Check if Ohmyzsh is installed
  stat:
    path: /home/lukcic/.oh-my-zsh
  register: result

- name: Install Ohmyzsh
  become_user: lukcic
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    chdir: /home/lukcic/autoinstall
  when: not result.stat.exists

- name: Install zsh-autosuggestions
  become_user: lukcic
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: /home/lukcic/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    clone: yes
    update: yes

- name: Install zsh-syntax-highlighting
  become_user: lukcic
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: /home/lukcic/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    clone: yes
    update: yes

- name: Install powerlevel10k
  become_user: lukcic
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: /home/lukcic/.oh-my-zsh/custom/themes/powerlevel10k
    depth: 1
    clone: yes
    update: yes

- name: Install tpm-tmux plugin
  become_user: lukcic
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: /home/lukcic/.tmux/plugins/tpm
    clone: yes
    update: yes

- name: Create batcat symbolic link
  become: true
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: /usr/bin/bat
    owner: root
    group: root
    state: link

- name: Override config files
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/home/lukcic/{{ item }}"
    owner: lukcic
    group: lukcic
  with_items:
    - .zshrc
    - .p10k.zsh
    - tmux.conf

- name: Change shell
  user:
    name: lukcic
    shell: /usr/bin/zsh
