- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - zsh
      - vim
      - tmux
      - bat
    state: present
    update_cache: true

- name: Create batcat symbolic link
  become: true
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: /usr/bin/bat
    owner: root
    group: root
    state: link

- name: Configure packages for user
  become: true
  become_user: lukcic
  block:
    - name: Create autoinstall directory
      ansible.builtin.file:
        path: /home/lukcic/autoinstall
        state: directory
        mode: '0700'

    - name: Check if Ohmyzsh is installed
      ansible.builtin.stat:
        path: /home/lukcic/.oh-my-zsh
      register: result

    - name: Install Ohmyzsh
      ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
      args:
        chdir: /home/lukcic/autoinstall
      when: not result.stat.exists
      register: zsh_install
      changed_when: zsh_install.rc != 0

    - name: Install zsh-autosuggestions
      ansible.builtin.git: # noqa: latest
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: /home/lukcic/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        clone: true
        update: true

    - name: Install zsh-syntax-highlighting
      ansible.builtin.git: # noqa: latest
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: /home/lukcic/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        clone: true
        update: true

    - name: Install powerlevel10k
      become: true
      become_user: lukcic
      ansible.builtin.git: # noqa: latest
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: /home/lukcic/.oh-my-zsh/custom/themes/powerlevel10k
        depth: 1
        clone: true
        update: true

    - name: Install tpm-tmux plugin
      become: true
      become_user: lukcic
      ansible.builtin.git: # noqa: latest
        repo: https://github.com/tmux-plugins/tpm
        dest: /home/lukcic/.tmux/plugins/tpm
        clone: true
        update: true

    - name: Override config files
      ansible.builtin.copy:
        src: '{{ role_path }}/files/{{ item }}'
        dest: '/home/lukcic/{{ item }}'
        owner: lukcic
        group: lukcic
        mode: '0700'
      with_items:
        - .zshrc
        - .p10k.zsh
        - .tmux.conf

- name: Change shell
  ansible.builtin.user:
    name: lukcic
    shell: /usr/bin/zsh

- name: Add aliasses
  ansible.builtin.include_tasks: '{{ role_path }}/tasks/aliases.yml'
