all_groups: # noqa: var-naming[no-role-prefix]
  - name: wheel

all_users: # noqa: var-naming[no-role-prefix]
  - name: ansible
    groups: wheel
    shell: /bin/bash
    uid: 3333

  - name: lukcic
    groups: wheel
    shell: /bin/bash
    uid: 3000
