- name: Install packages add users
  become: true
  hosts: all
  roles:
    - role: common/packages
      vars:
        extra_packages:
          - bat
    - role: common/users
    - role: common/shell
    - role: common/dist-upgrade
