- name: Install packages
  ansible.builtin.include_tasks: install.yml

- name: Generate config from templates
  ansible.builtin.include_tasks: templates.yml
  tags: templates

- name: Copy Bind configuration
  ansible.builtin.copy:
    src: '{{ role_path }}/files/config/{{ item }}'
    dest: '/etc/bind/{{ item }}'
    owner: root
    group: bind
    mode: 0644
  with_items:
    - 'named.conf.options'
    - 'rndc.conf'
    - 'tsig.key'
  register: bind_config_change

- name: Update /etc/bind permissions
  ansible.builtin.command: chmod g+w /etc/bind

- name: Create log directory
  ansible.builtin.file:
    path: /var/log/bind
    state: directory
    owner: bind

- name: Check config
  ansible.builtin.command: named-checkconf /etc/bind/named.conf

- name: Copy zone files
  ansible.builtin.copy:
    src: '{{ role_path }}/files/zones/'
    dest: '/etc/bind/'
    owner: root
    group: bind
    mode: 0644
    backup: yes
    force: true
  register: zone_config_change

- name: Freeze domains
  ansible.builtin.command:
    cmd: 'rndc freeze {{ item.domain }}'
  loop: '{{ zones }}'
  when: zone_config_change

- name: Enable named service
  ansible.builtin.service:
    name: named
    enabled: true
    state: started

- name: Reload (thaw) domains
  ansible.builtin.command:
    cmd: 'rndc thaw {{ item.domain }}'
  loop: '{{ zones }}'
  when: zone_config_change

- name: Restart Bind when config change
  ansible.builtin.service:
    name: named
    state: restarted
  when:
    - bind_config_change
    - zone_config_change

- name: Sync Bind journal cron
  ansible.builtin.cron:
    name: 'sync bind journal'
    special_time: hourly
    job: 'rndc sync'
    user: bind
