- name: Install packages
  include_tasks: install.yml

- name: Generate config from templates
  include_tasks: templates.yml
  tags: templates

- name: Copy Bind configuration
  copy:
    src: "{{ role_path }}/files/config/{{ item }}"
    dest: "/etc/bind/{{ item }}"
    owner: root
    group: bind
    mode: 0644
  with_items:
    - "named.conf.options"
    - "rndc.conf"
    - "tsig.key"
  register: bind_config_change

- name: Update /etc/bind permissions
  shell: chmod g+w /etc/bind

- name: Create log directory
  file:
    path: /var/log/bind
    state: directory
    owner: bind

- name: Check config
  shell: named-checkconf /etc/bind/named.conf

- name: Copy zone files
  copy:
    src: "{{ role_path }}/files/zones/"
    dest: "/etc/bind/"
    owner: root
    group: bind
    mode: 0644
    backup: yes
    force: true
  register: zone_config_change

- name: Enable named service
  service:
    name: named
    enabled: true
    state: started

- name: Restart Bind when config change
  service:
    name: named
    state: restarted
  when:
    - bind_config_change
    - zone_config_change

- name: Sync Bind journal cron
  cron:
    name: "sync bind journal"
    special_time: hourly
    job: "rndc sync"
    user: bind
