- name: Install required package
  apt:
    pkg:
      - bind9
      - bind9utils
      - bind9-doc
    state: latest
    update_cache: true
  run_once: true

- name: Create BIND configuration from template
  template:
    src: "templates/named.conf.options.j2"
    dest: "../../roles/named/files/config/named.conf.options"
  loop:
    "{{ zones }}"
    # - "rndc.conf"
    # - "tsig.key"
  become: false
  delegate_to: localhost
  tags:
    - templates

- name: Set timestamp
  set_fact:
    current_timestamp: "{{ '%Y%m%d%H%M%S' | strftime }}"
  become: false
  delegate_to: localhost
  tags:
    - templates

- name: Create forward zone files from templates
  template:
    src: "templates/db.forward.zone.j2"
    dest: "../../roles/named/files/zones/db.{{ item.domain }}"
  loop: "{{ zones }}"
  become: false
  delegate_to: localhost
  tags:
    - templates

- name: Create reverse zone files from templates
  template:
    src: "templates/db.reverse.zone.j2"
    dest: "../../roles/named/files/zones/db.{{ item.reverse or item.domain }}"
  loop: "{{ zones }}"
  when: item.reverse is defined
  become: false
  delegate_to: localhost
  tags:
    - templates

- name: Copy Bind configuration
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/etc/bind/{{ item }}"
    owner: root
    group: bind
    mode: 0644
  with_items:
    - "named.conf.options"
    - "rndc.conf"
    - "tsig.key"
  register: bind_config_change

- name: Update /etc/bind permissions
  shell: chmod g+w /etc/bind

- name: Create log directory
  file:
    path: /var/log/bind
    state: directory
    owner: bind

- name: Check config
  shell: named-checkconf /etc/bind/named.conf
  ignore_errors: true

- name: Check if zone file exists
  stat:
    path: "/etc/bind/db.{{ item.domain }}"
  with_items: "{{ zones }}"
  register: check_zone_file

- name: Copy zones configuration
  copy:
    src: "{{ role_path }}/files/zones/{{ item.item.file }}"
    dest: "/etc/bind/{{ item.item.file }}"
    owner: root
    group: bind
    mode: 0644
  when: not item.stat.exists
  with_items: "{{ check_zone_file.results }}"
  register: zone_config_change

- name: Enable named service
  service:
    name: named
    enabled: true
    state: started

- name: Restart Bind when config change
  service:
    name: named
    state: restarted
  when:
    - bind_config_change
    - zone_config_change

- name: Sync Bind journal cron
  cron:
    name: "sync bind journal"
    special_time: hourly
    job: "rndc sync"
    user: bind
