---
apiVersion: v1
kind: Namespace
metadata:
  name: photoprism
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: photoprism-config
  namespace: photoprism
data:
  PHOTOPRISM_AUTH_MODE: "password"
  PHOTOPRISM_SITE_URL: "http://foto.lukcic.pl/"
  PHOTOPRISM_UID: "568"
  PHOTOPRISM_GID: "568"
  PHOTOPRISM_HTTP_COMPRESSION: "gzip"
  PHOTOPRISM_LOG_LEVEL: "info"
