---
apiVersion: v1
kind: Namespace
metadata:
  name: photoprism
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: photoprism-config
  namespace: photoprism
data:
  PHOTOPRISM_AUTH_MODE: "password"
  PHOTOPRISM_SITE_URL: "https://foto.lukcic.pl/"
  PHOTOPRISM_UID: "568"
  PHOTOPRISM_GID: "568"
  PHOTOPRISM_HTTP_COMPRESSION: "gzip"
  PHOTOPRISM_LOG_LEVEL: "trace"
  PHOTOPRISM_DETECT_NSFW: "true"
  PHOTOPRISM_UPLOAD_NSFW: "true"
  PHOTOPRISM_DATABASE_DRIVER: "mysql"
  PHOTOPRISM_DATABASE_SERVER: "mariadb-photoprism:3306"
  PHOTOPRISM_DATABASE_NAME: "photoprism"
  PHOTOPRISM_DATABASE_USER: "photoprism"
