---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photoprism-storage
  labels:
    type: local
    name: photoprism-storage
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/photoprism/storage
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-storage
  namespace: photoprism
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      name: photoprism-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photoprism-originals
  labels:
    type: local
    name: photoprism-originals
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/photoprism/originals
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-originals
  namespace: photoprism
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      name: photoprism-originals
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photoprism-imports
  labels:
    type: local
    name: photoprism-imports
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/photoprism/imports
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-imports
  namespace: photoprism
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      name: photoprism-imports
