- name: Install and hold kube* packages
  tags:
    - vm
    - Debian
  block:
    - name: Add K8s signing key
      ansible.builtin.get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
        mode: '0644'

    - name: Add K8s repo
      ansible.builtin.apt_repository:
        repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /'
        state: present
        filename: /etc/apt/sources.list.d/kubernetes.list

    - name: Install K8s packages
      ansible.builtin.apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Hold K8s packages
      ansible.builtin.command:
        cmd: 'apt-mark hold {{ item }}'
      with_items:
        - kubelet
        - kubeadm
        - kubectl
      register: package_held
      changed_when: package_held.rc != 0

    - name: Install Ansible pre-requisites
      ansible.builtin.pip:
        name:
          - pyyaml
          - kubernetes
        break_system_packages: true
