- name: Create Homer config directory
  file:
    path: /etc/homer/assets
    state: directory
    mode: 0755
    group: ansible
    owner: ansible
  tags:
    - homer

- name: Copy Homer configuration
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/etc/homer/assets/{{ item }}"
    owner: ansible
    group: ansible
    mode: 0755
  with_items:
    - "config.yml"
    - "custom.css"
  tags:
    - homer
  register: homer_config_change

- name: Start compose
  community.docker.docker_compose:
    project_name: homer
    definition:
      version: "3.5"
      services:
        homer:
          image: b4bz/homer:v23.10.1
          container_name: homer
          restart: unless-stopped
          volumes:
            - /etc/homer/assets/:/www/assets:rw
          environment:
            - UID=1000
            - GID=1002
          ports:
            - 8080:8080
  tags:
    - homer
