- name: Start compose
  community.docker.docker_compose:
    project_name: nginxproxymanager
    definition:
      version: "3.5"
      volumes:
        nginxproxymanager-data:
        nginxproxymanager-ssl:
        nginxproxymanager-db:
      services:
        nginxproxymanager:
          container_name: nginx
          restart: unless-stopped
          image: jc21/nginx-proxy-manager:2.10.3
          ports:
            - 80:80
            - 81:81
            - 443:443
          volumes:
            - nginxproxymanager-data:/data
            - nginxproxymanager-ssl:/etc/letsencrypt
          environment:
            - DB_MYSQL_HOST=nginxproxymanager-db
            - DB_MYSQL_PORT=3306
            - DB_MYSQL_USER=npm
            - DB_MYSQL_PASSWORD={{ db_user_password }}
            - DB_MYSQL_NAME=npm
          healthcheck:
            test: ["CMD", "/bin/check-health"]
            interval: 1m
            timeout: 10s
            retries: 3
            start_period: 30s
          depends_on:
            - nginxproxymanager-db
        nginxproxymanager-db:
          image: jc21/mariadb-aria:10.4.15
          container_name: mariadb
          restart: unless-stopped
          volumes:
            - nginxproxymanager-db:/var/lib/mysql
          environment:
            - MYSQL_ROOT_PASSWORD={{ db_root_password }}
            - MYSQL_DATABASE=npm
            - MYSQL_USER=npm
            - MYSQL_PASSWORD={{ db_user_password }}
