name: '[HOMELAB] Deploy DSN Entries'

on:
  workflow_dispatch:
  push:
    paths:
      - ansible/roles/named/vars/main.yml

env:
  ANSIBLE_FORCE_COLOR: true

jobs:
  update_dns_zones:
    timeout-minutes: 20
    runs-on: self-hosted
    steps:
      - name: Cleanup build folder
        run: |
          sudo ls -la ./
          sudo rm -rf ./* || true
          sudo rm -rf ./.??* || true
          sudo ls -la ./

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.3.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      # - name: Setup SSH
      #   uses: webfactory/ssh-agent@v0.9.0
      #   with:
      #     ssh-private-key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        env:
          ANSIBLE_ROLES_PATH: "${{ github.workspace }}/ansible/roles"
          ANSIBLE_SSH_COMMON_ARGS: "-vvv -o KexAlgorithms=ecdh-sha2-nistp521"
        with:
          playbook: main.yml
          directory: ./ansible/sites/ns1.lukcic.net
          configuration: |
            [defaults]
            roles_path=../../roles
            deprecation_warnings=False
            host_key_checking=False
            command_timeout=40
          # key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
          inventory: |
            lxc_root ansible_host=192.168.254.53 ansible_user=root ansible_private_key_file=$HOME/.ssh/proxmox-lxc-root.pem
            lxc_ansible ansible_host=192.168.254.53 ansible_user=ansible ansible_private_key_file=$HOME/.ssh/ansible-key-ecdsa.pem
          options: |
            -vvv