name: '[HOMELAB] Deploy DSN Entries'

on:
  workflow_dispatch:
  push:
    paths:
      - ansible/roles/named/vars/main.yml

env:
  ANSIBLE_FORCE_COLOR: true

jobs:
  update_dns_zones:
    timeout-minutes: 20
    runs-on: self-hosted
    steps:
      - name: Cleanup build folder
        run: |
          sudo ls -la ./
          sudo rm -rf ./* || true
          sudo rm -rf ./.??* || true
          sudo ls -la ./

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.3.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Run ansible playbook
        run: ansible-playbook main.yml -vvv
        working-directory: ./ansible/sites/ns1.lukcic.net
        env:
          ANSIBLE_INVENTORY: "${{ github.workspace }}/ansible/sites/ns1.lukcic.net/inventory-ns1" 
          ANSIBLE_CONFIG: "${{ github.workspace }}/ansible/ansible.cfg"
          ANSIBLE_ROLES_PATH: "${{ github.workspace }}/ansible/roles"
          ANSIBLE_SSH_COMMON_ARGS: "-vvvv -o KexAlgorithms=ecdh-sha2-nistp521 -o ControlPersist=30m"
