name: '[HOMELAB] Deploy DSN Entries'

on:
  workflow_dispatch:
  push:
    paths:
      - ansible/sites/ns1/vars.yml

env:
  ANSIBLE_FORCE_COLOR: true

jobs:
  update_dns_zones:
    timeout-minutes: 20
    runs-on: self-hosted
    steps:
      - name: Cleanup build folder
        run: |
          sudo ls -la ./
          sudo rm -rf ./* || true
          sudo rm -rf ./.??* || true
          sudo ls -la ./

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.3.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Export TSIG key
        run: |
          cat << EOF > ${{ github.workspace }}/ansible/roles/named/files/config/tsig.key
          ${{ secrets.TSIG_KEY }}
          EOF

      - name: Run ansible playbook
        run: ansible-playbook main.yml --tags "named"
        working-directory: ./ansible/sites/ns1
        env:
          ANSIBLE_INVENTORY: "${{ github.workspace }}/ansible/sites/ns1/inventory-ns1" 
          ANSIBLE_CONFIG: "${{ github.workspace }}/ansible/ansible.cfg"
          ANSIBLE_ROLES_PATH: "${{ github.workspace }}/ansible/roles"
