postgresql_service_state: started
postgresql_service_enabled: true
postgresql_restarted_state: "restarted"
postgresql_python_library: python3-psycopg2
postgresql_user: postgres
postgresql_group: postgres
postgresql_unix_socket_directories:
  - /var/run/postgresql
postgres_users_no_log: false

postgresql_databases:
  - name: paperless
    login_password: paperless
    login_user: paperless
    port: 5432
    owner: paperless
    state: present

postgresql_users:
  - name: paperless
    password: paperless
    encrypted: true
    db: paperless
    login_host: "0.0.0.0"
    login_password: paperless
    login_user: paperless
    port: 5432
    state: present

postgresql_hba_entries:
  - { type: local, database: all, user: postgres, auth_method: peer }
  - { type: local, database: all, user: paperless, auth_method: peer }
  - { type: local, database: all, user: all, auth_method: peer }
